language: node_js
sudo: required
node_js:
- 10.16.0
branchs:
  only:
    - master
addons:
  ssh_known_hosts:
    - 101.37.13.125
cache:
  directories:
   - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_28b4b9e40eeb_key -iv $encrypted_28b4b9e40eeb_iv  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 开启 ssh-agent，即允许使用 ssh 命令
  - eval "$(ssh-agent -s)"
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 ~/.ssh/id_rsa
  # 将私钥添加到 ssh
  - ssh-add ~/.ssh/id_rsa

  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
after_success:
  - ls -a && echo 'success'